# Generated by Django 4.1.7 on 2024-07-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_purchases_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
