# Generated by Django 4.1.13 on 2024-06-26 13:15

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP\\Downloads\\micro-ecommerce\\local-cdn\\protected'), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
